language: node_js
node_js:
  - "12"

install:
  - cd app && npm install
  - npm run dist
  - cd ../frontend && npm install
  - npm run build

after_script:
  - ls -l
  - cd ../app && ls -l

deploy:
  provider: releases
  api_key: "37695e73abce933eac09314a1a5f1c53ca6e67f0"
  file: "../app/station"
  skip_cleanup: true
  on:
    tags: true

