language: node_js
node_js:
  - "12"

install:
  - cd app && npm install
  - npm run dist

after_script:
  - ls -l
  - cd ../app && ls -l

deploy:
  provider: releases
  api_key: "589fb3431175c0f655de7a99d5ac7beb4a4acef1"
  file: "../app/station"
  skip_cleanup: true
  on:
    tags: true

