language: node_js
node_js:
  - "12"

install:
  - cd app && npm install
  - npm run dist

after_install:
  - ls -l
  - cd ..

deploy:
  provider: releases
  api_key: "70c547404d58a2667994a706169d3647ab13a11a"
  file: "app/station"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

