language: node_js
node_js:
  - "12"

install:
  - cd app && npm install
  - npm run dist

after_install:
  - ls -l
  - cd ..

deploy:
  provider: releases
  api_key: "27d0f5980c2c58eacccbc7dce24517912846d94b"
  file: "app/station"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

